#!/bin/bash

cmd=$(which rustfmt)

if [ -n "$cmd" ]
then
    IFS=$'\n'

    for line in $(git status -s)
    do
        if [[ $line == A* || $line == M* ]]
        then
            if [[ $line == *.rs ]]
            then
                $cmd {line:3}
                git add {line:3}
            fi
        fi
    done

else
    echo "rustfmt was not found"
fi
